# Generated by Django 4.2.11 on 2024-04-12 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='security.applicationmodel'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
    ]
