# Generated by Django 4.2.11 on 2024-04-13 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0002_twofactorsettingsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorsettingsmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL),
        ),
    ]
