# Generated by Django 4.2.11 on 2024-04-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_remove_applicationmodel_is_2fa_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='twofactorsettingsmodel',
            table='tsec_two_factor_settings',
        ),
    ]
