# Generated by Django 4.2.11 on 2024-04-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0005_alter_twofactorsettingsmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=600)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_token', models.CharField(blank=True, max_length=600, null=True)),
                ('expired', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_offline', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_no_ready', models.FloatField(blank=True, default=0, null=True)),
                ('offline', models.BooleanField(default=False)),
                ('device', models.CharField(default='unknown', max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('touch_capable', 'Touch Capable'), ('pc', 'PC'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=80)),
                ('browser', models.CharField(default='unknown', max_length=255)),
                ('browser_version', models.CharField(default='unknown', max_length=80)),
                ('system_operation', models.CharField(default='unknown', max_length=255)),
                ('system_operation_version', models.CharField(default='unknown', max_length=80)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('finalized', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_histories', to='security.applicationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'tsec_session_histories',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=600)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_token', models.CharField(blank=True, max_length=600, null=True)),
                ('expire', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.BooleanField(default=False)),
                ('last_offline', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_no_ready', models.FloatField(blank=True, default=0, null=True)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('device', models.CharField(default='unknown', max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('touch_capable', 'Touch Capable'), ('pc', 'PC'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=80)),
                ('browser', models.CharField(default='unknown', max_length=255)),
                ('browser_version', models.CharField(default='unknown', max_length=80)),
                ('system_operation', models.CharField(default='unknown', max_length=255)),
                ('system_operation_version', models.CharField(default='unknown', max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='security.applicationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'tsec_sessions',
                'unique_together': {('user', 'ip_address', 'application')},
            },
        ),
    ]
