# Generated by Django 4.2.11 on 2024-04-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_applicationmodel_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='historicalapplicationmodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Application', 'verbose_name_plural': 'historical Applications'},
        ),
    ]
